on:
  push:
    branches:
      - main
name: Deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USER }}
          PORT: "22"
          KEY: ${{ secrets.VPS_SSH_KEY }}
        with:
          envs: host, username, port, key
          source: "."
          target: "/home/apps/leilaofake_webapp"
          